export const FETCH_COMPANIES_BEGIN = "FETCH_COMPANIES_BEGIN";
export const FETCH_COMPANIES_SUCCESS = "FETCH_COMPANIES_SUCCESS";
export const FETCH_COMPANIES_FAILED = "FETCH_COMPANIES_FAILED";

export const ADD_COMPANIES_BEGIN = "ADD_COMPANIES_BEGIN";
export const ADD_COMPANIES_SUCCESS = "ADD_COMPANIES_SUCCESS";
export const ADD_COMPANIES_FAILED = "ADD_COMPANIES_FAILED";

export const UPDATE_COMPANIES_BEGIN = "UPDATE_COMPANIES_BEGIN";
export const UPDATE_COMPANIES_SUCCESS = "UPDATE_COMPANIES_SUCCESS";
export const UPDATE_COMPANIES_FAILED = "UPDATE_COMPANIES_FAILED";

export const DELETE_COMPANIES_BEGIN = "DELETE_COMPANIES_BEGIN";
export const DELETE_COMPANIES_SUCCESS = "DELETE_COMPANIES_SUCCESS";
export const DELETE_COMPANIES_FAILED = "DELETE_COMPANIES_FAILED";
